spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
    open-in-view: false

fetch:
  api:
    base-url: ${API_BASE_URL}
    api-key: ${API_KEY}
    fetch-interval: ${FETCH_INTERVAL:300000}

    accident:
      info-url: ${API_ACCIDENT_INFO_URL:AccInfo/1/1000/}
      type-url: ${API_ACCIDENT_TYPE_URL:AccMainCode/1/100/}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: INFO
